<?php
/**
 * The wording, in the three languages the ladder application itself speaks.
 *
 * Not gettext, deliberately. The strings here are the only wording the ladder has: the application
 * sends codes and numbers — a rank class, a finding, the reason somebody was given points by hand —
 * and this file is where each becomes a sentence. Keeping the three languages side by side in one
 * readable file is what makes a missing one visible.
 *
 * A `bonus_*` key is named after the code the API sends, so BHO_Render looks one up rather than
 * matching on a list it holds itself; a code with no key here falls back to the note beside it.
 *
 * The three placings are worded short — "1. Platz", not "Turnierbonus 1. Platz" — because the event
 * is printed in front of them and the block they sit in is already headed "Bonuspunkte". Saying
 * "Turnierbonus" between those two would be the third time. A .po/.mo pair would put the German in a
 * compiled binary and add a build step to a plugin that otherwise has none.
 *
 * English unless the setting says otherwise — blackhydra.org is an English page, and following the
 * WordPress locale would put a German table on it the moment the site runs a German install.
 * `bho_ladder_strings` is a filter, so a site can correct a word without editing the plugin.
 */

declare(strict_types=1);

defined('ABSPATH') || exit;

/** @return array<string,string> */
function bho_ladder_strings(): array
{
    $all = [
        'de' => [
            'all_games' => 'Alle Spiele ansehen →',
            'games_total' => '%1$d Spiele · Seite %2$d von %3$d',
            'day' => 'Datum',
            'tournament' => 'Turnier',
            'round' => 'Rd.',
            'score' => 'Ergebnis',
            'opponent' => 'Gegner',
            'previous' => '← Neuere',
            'next' => 'Ältere →',
            'page_of' => 'Seite %1$d von %2$d',
            'ladder' => 'Ladder',
            'back' => '← Zur Ladder',
            'player' => 'Spieler',
            'rating' => 'Punkte',
            'rank' => 'Rang',
            'record' => 'S–U–N',
            'events' => 'Turniere',
            'sort_by' => 'Nach %s sortieren',
            'running_one' => 'Laufendes Turnier',
            'running_many' => 'Laufende Turniere',
            'updated' => 'Stand %s',
            'herald' => 'Tabletop Herald ↗',
            'latest' => 'Letzte Spiele',
            'empty' => 'Bisher wurde nichts importiert.',
            'unavailable' => 'Die Ladder ist gerade nicht erreichbar.',
            'stale' => 'Zuletzt bekannter Stand — die Ladder war beim Aktualisieren nicht erreichbar.',
            'games' => 'Spiele',
            'rules' => 'Regeln',
            'start_rating' => 'Startpunkte',
            'per_game' => 'Punkte pro Spiel, je nach Klasse des Gegners',
            'vs_higher' => 'höher',
            'vs_same' => 'gleiche Klasse',
            'vs_lower' => 'tiefer',
            'bonus' => 'Turnierbonus',
            'bonus_note' => 'wenn alle Runden gespielt sind',
            'rank_classes' => 'Rangklassen',
            'rank_then' => 'Rangklasse bei diesem Spiel: %s',
            'no_games' => 'Noch keine Spiele.',
            'no_player' => 'Diesen Spieler gibt es nicht.',
            'from_1100' => 'von 1100',
            'here' => 'hier',
            'games_count' => '%1$s aus %2$d Spielen',
            'win' => 'Sieg',
            'draw' => 'Remis',
            'loss' => 'Niederlage',
            'versus' => 'vs',
            'not_counted' => 'zählt nicht',
            'below' => 'unter %d',
            'upwards' => 'ab %d',
            'first' => 'Erster Platz',
            'second' => 'Zweiter Platz',
            'third' => 'Dritter Platz',
            'bonus_points' => 'Bonuspunkte',
            'bonus_reason' => 'Grund',
            'bonus_tournamentFirst' => '1. Platz',
            'bonus_tournamentSecond' => '2. Platz',
            'bonus_tournamentThird' => '3. Platz',
            'bonus_tournamentOther' => 'Turnierbonus',
            'bonus_tournamentPlacing' => 'Turnierwertung',
            'bonus_other' => 'Sonstige',
        ],
        'en' => [
            'all_games' => 'See every game →',
            'games_total' => '%1$d games · page %2$d of %3$d',
            'day' => 'Date',
            'tournament' => 'Tournament',
            'round' => 'Rd.',
            'score' => 'Score',
            'opponent' => 'Opponent',
            'previous' => '← Newer',
            'next' => 'Older →',
            'page_of' => 'Page %1$d of %2$d',
            'ladder' => 'Ladder',
            'back' => '← Back to the ladder',
            'player' => 'Player',
            'rating' => 'Rating',
            'rank' => 'Rank',
            'record' => 'W–D–L',
            'events' => 'Events',
            'sort_by' => 'Sort by %s',
            'running_one' => 'Tournament in progress',
            'running_many' => 'Tournaments in progress',
            'updated' => 'Updated %s',
            'herald' => 'Tabletop Herald ↗',
            'latest' => 'Latest games',
            'empty' => 'Nothing has been imported so far.',
            'unavailable' => 'The ladder cannot be reached at the moment.',
            'stale' => 'Last known standings — the ladder could not be reached when this was refreshed.',
            'games' => 'Games',
            'rules' => 'Rules',
            'start_rating' => 'Everyone starts at',
            'per_game' => 'Points per game, by the opponent’s class',
            'vs_higher' => 'higher',
            'vs_same' => 'same class',
            'vs_lower' => 'lower',
            'bonus' => 'Tournament bonus',
            'bonus_note' => 'once all rounds are played',
            'rank_classes' => 'Rank classes',
            'rank_then' => 'Class when this game was played: %s',
            'no_games' => 'No games yet.',
            'no_player' => 'No such player.',
            'from_1100' => 'from 1100',
            'here' => 'here',
            'games_count' => '%1$s across %2$d games',
            'win' => 'Win',
            'draw' => 'Draw',
            'loss' => 'Loss',
            'versus' => 'vs',
            'not_counted' => 'not counted',
            'below' => 'below %d',
            'upwards' => '%d and up',
            'first' => 'First place',
            'second' => 'Second place',
            'third' => 'Third place',
            'bonus_points' => 'Bonus points',
            'bonus_reason' => 'Reason',
            'bonus_tournamentFirst' => '1st place',
            'bonus_tournamentSecond' => '2nd place',
            'bonus_tournamentThird' => '3rd place',
            'bonus_tournamentOther' => 'Tournament bonus',
            'bonus_tournamentPlacing' => 'Tournament result',
            'bonus_other' => 'Other',
        ],
        'es' => [
            'all_games' => 'Ver todas las partidas →',
            'games_total' => '%1$d partidas · página %2$d de %3$d',
            'day' => 'Fecha',
            'tournament' => 'Torneo',
            'round' => 'Rd.',
            'score' => 'Resultado',
            'opponent' => 'Rival',
            'previous' => '← Más recientes',
            'next' => 'Más antiguas →',
            'page_of' => 'Página %1$d de %2$d',
            'ladder' => 'Ladder',
            'back' => '← Volver a la ladder',
            'player' => 'Jugador',
            'rating' => 'Puntos',
            'rank' => 'Rango',
            'record' => 'V–E–D',
            'events' => 'Torneos',
            'sort_by' => 'Ordenar por %s',
            'running_one' => 'Torneo en curso',
            'running_many' => 'Torneos en curso',
            'updated' => 'Actualizado %s',
            'herald' => 'Tabletop Herald ↗',
            'latest' => 'Últimas partidas',
            'empty' => 'Todavía no se ha importado nada.',
            'unavailable' => 'No se puede contactar con la ladder en este momento.',
            'stale' => 'Última clasificación conocida — no se pudo contactar con la ladder al actualizar.',
            'games' => 'Partidas',
            'rules' => 'Reglas',
            'start_rating' => 'Todos empiezan en',
            'per_game' => 'Puntos por partida, según la clase del rival',
            'vs_higher' => 'superior',
            'vs_same' => 'misma clase',
            'vs_lower' => 'inferior',
            'bonus' => 'Bonus de torneo',
            'bonus_note' => 'cuando se juegan todas las rondas',
            'rank_classes' => 'Clases',
            'rank_then' => 'Clase al jugar esta partida: %s',
            'no_games' => 'Aún no hay partidas.',
            'no_player' => 'Ese jugador no existe.',
            'from_1100' => 'desde 1100',
            'here' => 'aquí',
            'games_count' => '%1$s en %2$d partidas',
            'win' => 'Victoria',
            'draw' => 'Empate',
            'loss' => 'Derrota',
            'versus' => 'vs',
            'not_counted' => 'no cuenta',
            'below' => 'por debajo de %d',
            'upwards' => '%d o más',
            'first' => 'Primer puesto',
            'second' => 'Segundo puesto',
            'third' => 'Tercer puesto',
            'bonus_points' => 'Puntos extra',
            'bonus_reason' => 'Motivo',
            'bonus_tournamentFirst' => '1.º puesto',
            'bonus_tournamentSecond' => '2.º puesto',
            'bonus_tournamentThird' => '3.º puesto',
            'bonus_tournamentOther' => 'Bonus de torneo',
            'bonus_tournamentPlacing' => 'Resultado del torneo',
            'bonus_other' => 'Otros',
        ],
    ];

    $choice = BHO_Settings::all()['language'];
    $short = $choice === 'site' ? strtolower(substr(get_locale(), 0, 2)) : $choice;

    return apply_filters('bho_ladder_strings', $all[$short] ?? $all['en'], $short);
}
